### ISSUE TITLE
pgDesigner

### ISSUE THREAD

**Issue by lucaarcteam** [archeos/archeos-menu#2]
The entry for the software pgDesigner should be added in the Databases menu

**Comment by fabfurnari** [comment]
Is this still needed? I cannot find pgdesigner in wheezy repositories...

**Comment by lucaarcteam** [comment]
Nope, PgDesiner will be no longer support. If we will be able we will rplace it with PgModeler in ArcheOS-next. Otherwise we will simply dismiss this software.
